// Generated by CoffeeScript 1.6.2
(function() {
  var CommonTool, RoadTool, SharpTurnTool, StraightRoadTool, Tool, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  root = this;

  Tool = (function() {
    function Tool() {
      console.log("setting tool", this);
      tools.current = this;
    }

    return Tool;

  })();

  CommonTool = (function(_super) {
    __extends(CommonTool, _super);

    function CommonTool() {
      CommonTool.__super__.constructor.call(this);
      layers.tool.clear();
    }

    CommonTool.prototype.over = function(ent, e) {
      var dist, handle, selected, shortest, _i, _len, _ref;

      if (ent instanceof ents.Node) {
        shortest = 9007199254740992;
        selected = null;
        _ref = ent.handels;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          handle = _ref[_i];
          dist = P(e).distance(handle.pos);
          if (dist < shortest) {
            selected = handle;
            shortest = dist;
          }
        }
        return new RoadTool(selected);
      }
    };

    return CommonTool;

  })(Tool);

  RoadTool = (function(_super) {
    __extends(RoadTool, _super);

    function RoadTool(handle) {
      this.handle = handle != null ? handle : null;
      this.click = __bind(this.click, this);
      RoadTool.__super__.constructor.call(this);
      this.endNode = null;
    }

    RoadTool.prototype.click = function(e) {
      var nextHandle;

      if (this.curve != null) {
        layers.main.drawBeizer(this.curve);
        nextHandle = ents.makeRoad(this.handle, this.curve.p3, this.curve.p2, this.curve, this.endNode);
        return tools.current = new RoadTool(nextHandle);
      }
    };

    RoadTool.prototype.over = function(ent, e) {
      var color, curve;

      if (ent instanceof ents.Node) {
        curve = C.fromHandle(this.handle, ent.pos);
        color = this.check(curve);
        if (color != null) {
          this.draw(color);
          return this.endNode = ent;
        }
      }
    };

    RoadTool.prototype.out = function(ent, e) {
      if (ent instanceof ents.Node) {
        return this.endNode = null;
      }
    };

    RoadTool.prototype.move = function(e) {
      var curve;

      if (this.endNode == null) {
        curve = C.fromHandle(this.handle, P(e));
        return this.draw(this.check(curve));
      }
    };

    RoadTool.prototype.check = function(curve) {
      var angle, color, hue, k, len, rad, v, _ref;

      angle = Math.abs(L(curve.p0, curve.p1).signedAngle(L(curve.p2, curve.p3)));
      len = curveLen(curve);
      rad = (len * ((2 * Math.PI) / angle)) / (2 * Math.PI);
      if (angle > Math.PI / 2) {
        new SharpTurnTool(this.handle);
      }
      if (!(rad < 15 || L(curve.p1, curve.p2).length() > L(curve.p0, curve.p3).length())) {
        hue = 0;
        _ref = root.colorSpeed;
        for (k in _ref) {
          v = _ref[k];
          if (rad > new Number(k)) {
            hue = Math.max(v, hue);
          }
        }
        color = "hsb(" + hue + ", 0.9, 0.5)";
        this.curve = curve;
      }
      console.log(angle, len, rad, color);
      return color;
    };

    RoadTool.prototype.draw = function(color) {
      var edge, road, _i, _len, _ref, _results;

      layers.tool.clear();
      if (this.curve != null) {
        layers.tool.drawBeizer(this.curve, color);
      }
      _ref = this.handle.inverse.edges;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        edge = _ref[_i];
        _results.push((function() {
          var _j, _len1, _ref1, _results1;

          _ref1 = edge.roads;
          _results1 = [];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            road = _ref1[_j];
            _results1.push(layers.tool["drawRoad" + road.shape](road, "rgba(255,30,30,0.5)"));
          }
          return _results1;
        })());
      }
      return _results;
    };

    RoadTool.prototype.keyDown = function(e) {
      if (e.which === 17) {
        return tools.current = new StraightRoadTool(this.node);
      }
    };

    return RoadTool;

  })(Tool);

  root.colorSpeed = {
    15: 0,
    30: 0.05,
    55: 0.10,
    90: 0.15,
    135: 0.20,
    195: 0.25,
    250: 0.30,
    335: 0.35,
    435: 0.40,
    560: 0.45,
    755: 0.50
  };

  SharpTurnTool = (function(_super) {
    __extends(SharpTurnTool, _super);

    function SharpTurnTool(handle) {
      this.handle = handle;
      SharpTurnTool.__super__.constructor.call(this);
    }

    SharpTurnTool.prototype.click = function(e) {
      var nextHandle;

      if (this.line != null) {
        nextHandle = ents.makeRoad(this.handle, this.line.p1, this.line.p0, null, this.endNode);
        return new RoadTool(nextHandle);
      }
    };

    SharpTurnTool.prototype.move = function(e) {
      var curve;

      if (this.endNode == null) {
        curve = C.fromHandle(this.handle, P(e));
        this.line = L(this.handle.node.pos, P(e));
        this.check(curve);
        return this.draw();
      }
    };

    SharpTurnTool.prototype.over = function(ent, e) {
      var curve;

      if (ent instanceof ents.Node) {
        curve = C.fromHandle(this.handle, ent.pos);
        this.line = L(this.handle.node.pos, ent.pos);
        this.check(curve);
        this.endNode = ent;
        return this.draw();
      }
    };

    SharpTurnTool.prototype.out = function(ent, e) {
      if (ent instanceof ents.Node) {
        return this.endNode = null;
      }
    };

    SharpTurnTool.prototype.check = function(curve) {
      var angle;

      angle = Math.abs(L(curve.p0, curve.p1).signedAngle(L(curve.p2, curve.p3)));
      console.log("angle", angle);
      if (angle <= Math.PI / 2) {
        if (!(L(curve.p1, curve.p2).length() > L(curve.p0, curve.p3).length())) {
          return new RoadTool(this.handle);
        }
      }
    };

    SharpTurnTool.prototype.draw = function() {
      layers.tool.clear();
      return layers.tool.drawStraightRoad(this.line);
    };

    return SharpTurnTool;

  })(Tool);

  StraightRoadTool = (function(_super) {
    __extends(StraightRoadTool, _super);

    function StraightRoadTool(node) {
      this.node = node != null ? node : null;
      StraightRoadTool.__super__.constructor.call(this);
    }

    StraightRoadTool.prototype.click = function(e) {
      var line, node;

      line = this.straightLineFromNode(this.node, P(e));
      layers.main.drawLine(line);
      node = new ents.Node(line.p1, line.p0);
      return tools.current = new RoadTool(node);
    };

    StraightRoadTool.prototype.move = function(e) {
      var line;

      layers.tool.clear();
      line = this.straightLineFromNode(this.node, P(e));
      return layers.tool.drawLine(line);
    };

    StraightRoadTool.prototype.straightLineFromNode = function(node, pos) {
      var line, loc;

      line = L(node.pos, node.ctrl).growAdd(1000);
      loc = jsBezier.nearestPointOnCurve(pos, this.lineToBez(line)).location;
      return L(node.pos, node.ctrl).growAdd(1000 * loc);
    };

    StraightRoadTool.prototype.lineToBez = function(l) {
      return [
        {
          x: l.p0.x,
          y: l.p0.y
        }, {
          x: l.p0.x,
          y: l.p0.y
        }, {
          x: l.p1.x,
          y: l.p1.y
        }, {
          x: l.p1.x,
          y: l.p1.y
        }
      ];
    };

    StraightRoadTool.prototype.keyUp = function(e) {
      if (e.which === 17) {
        return tools.current = new RoadTool(this.node);
      }
    };

    return StraightRoadTool;

  })(Tool);

  root.tools = {};

  root.tools.RoadTool = RoadTool;

  root.tools.CommonTool = CommonTool;

}).call(this);
