// Generated by CoffeeScript 1.6.2
/*
The Player object; an Actor controlled by user input.
*/


/*
Keys used for various directions.
*/


/*
An array of image file paths to pre-load.
*/


/*
A magic-named function where all updates should occur.

@param {Number} delta
The amount of time since the last update. Use this to smooth movement.
This has the same value as the global `App.physicsDelta`.
@param {Number} timeElapsed
The amount of time elapsed while animating. This is useful for time-based
movement and limiting the frequency of events. This has the same value as
the global `App.physicsTimeElapsed`.
*/


(function() {
  var draw, keys, player, preloadables, setup, update;

  update = function(delta, timeElapsed) {
    return root.my.update(delta, timeElapsed);
  };

  /*
  A magic-named function where all drawing should occur.
  */


  draw = function() {
    context.drawCheckered(80, 0, 0, world.width, world.height);
    return player.draw();
  };

  /*
  A magic-named function for one-time setup.
  
  @param {Boolean} first
  true if the app is being set up for the first time; false if the app has
  been reset and is starting over.
  */


  setup = function(first) {
    var player;

    world.resize(canvas.width + 200, canvas.height + 200);
    Actor.prototype.GRAVITY = false;
    return player = new Player();
  };

  player = void 0;

  keys = {
    up: ["up", "w"],
    down: ["down", "s"],
    left: ["left", "a"],
    right: ["right", "d"]
  };

  preloadables = [];

}).call(this);

/*
//@ sourceMappingURL=main2.map
*/
